/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyReport {
  'programProblemSolvingScore' : bigint,
  'waliSantriResponseScore' : bigint,
  'date' : Time,
  'totalScore' : bigint,
  'teacherControlScore' : bigint,
  'attendanceScore' : bigint,
  'classControlScore' : bigint,
  'attendancePhoto' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface RankedDailyReport {
  'kepsek' : Principal,
  'dailyReport' : DailyReport,
}
export interface School {
  'region' : string,
  'active' : boolean,
  'name' : string,
  'principalName' : string,
}
export interface SchoolSummary { 'principal' : Principal, 'school' : School }
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActiveSchoolsCount' : ActorMethod<[], bigint>,
  'getActiveSchoolsList' : ActorMethod<[], Array<SchoolSummary>>,
  'getAllDailyReportsForKepsek' : ActorMethod<[], Array<DailyReport>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyReport' : ActorMethod<[Principal, Time], [] | [DailyReport]>,
  'getSchool' : ActorMethod<[Principal], [] | [School]>,
  'getTodayReports' : ActorMethod<[], Array<RankedDailyReport>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveDailyReport' : ActorMethod<[DailyReport], undefined>,
  'saveSchool' : ActorMethod<[School], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];