/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const School = IDL.Record({
  'region' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'principalName' : IDL.Text,
});
export const SchoolSummary = IDL.Record({
  'principal' : IDL.Principal,
  'school' : School,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DailyReport = IDL.Record({
  'catatanPresensi' : IDL.Text,
  'catatanWaliSantri' : IDL.Text,
  'programProblemSolvingScore' : IDL.Nat,
  'waliSantriResponseScore' : IDL.Nat,
  'departureTime' : Time,
  'date' : Time,
  'totalScore' : IDL.Nat,
  'catatanMonitoringGuru' : IDL.Text,
  'teacherControlScore' : IDL.Nat,
  'catatanPermasalahanProgram' : IDL.Text,
  'attendanceScore' : IDL.Nat,
  'classControlScore' : IDL.Nat,
  'catatanAmatanKelas' : IDL.Text,
  'attendancePhoto' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DailyMonitoringRow = IDL.Record({
  'report' : IDL.Opt(DailyReport),
  'principal' : IDL.Principal,
  'school' : School,
});
export const RankedDailyReport = IDL.Record({
  'kepsek' : IDL.Principal,
  'dailyReport' : DailyReport,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getActiveSchoolsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getActiveSchoolsList' : IDL.Func([], [IDL.Vec(SchoolSummary)], ['query']),
  'getAllDailyReportsForKepsek' : IDL.Func(
      [],
      [IDL.Vec(DailyReport)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyMonitoringRows' : IDL.Func(
      [Time],
      [IDL.Vec(DailyMonitoringRow)],
      ['query'],
    ),
  'getDailyReport' : IDL.Func(
      [IDL.Principal, Time],
      [IDL.Opt(DailyReport)],
      ['query'],
    ),
  'getReportsForDate' : IDL.Func(
      [Time],
      [IDL.Vec(RankedDailyReport)],
      ['query'],
    ),
  'getSchool' : IDL.Func([IDL.Principal], [IDL.Opt(School)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDailyReport' : IDL.Func([DailyReport], [], []),
  'saveSchool' : IDL.Func([School], [], []),
  'saveSchoolForPrincipal' : IDL.Func([IDL.Principal, School], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const School = IDL.Record({
    'region' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'principalName' : IDL.Text,
  });
  const SchoolSummary = IDL.Record({
    'principal' : IDL.Principal,
    'school' : School,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DailyReport = IDL.Record({
    'catatanPresensi' : IDL.Text,
    'catatanWaliSantri' : IDL.Text,
    'programProblemSolvingScore' : IDL.Nat,
    'waliSantriResponseScore' : IDL.Nat,
    'departureTime' : Time,
    'date' : Time,
    'totalScore' : IDL.Nat,
    'catatanMonitoringGuru' : IDL.Text,
    'teacherControlScore' : IDL.Nat,
    'catatanPermasalahanProgram' : IDL.Text,
    'attendanceScore' : IDL.Nat,
    'classControlScore' : IDL.Nat,
    'catatanAmatanKelas' : IDL.Text,
    'attendancePhoto' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const DailyMonitoringRow = IDL.Record({
    'report' : IDL.Opt(DailyReport),
    'principal' : IDL.Principal,
    'school' : School,
  });
  const RankedDailyReport = IDL.Record({
    'kepsek' : IDL.Principal,
    'dailyReport' : DailyReport,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getActiveSchoolsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getActiveSchoolsList' : IDL.Func([], [IDL.Vec(SchoolSummary)], ['query']),
    'getAllDailyReportsForKepsek' : IDL.Func(
        [],
        [IDL.Vec(DailyReport)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyMonitoringRows' : IDL.Func(
        [Time],
        [IDL.Vec(DailyMonitoringRow)],
        ['query'],
      ),
    'getDailyReport' : IDL.Func(
        [IDL.Principal, Time],
        [IDL.Opt(DailyReport)],
        ['query'],
      ),
    'getReportsForDate' : IDL.Func(
        [Time],
        [IDL.Vec(RankedDailyReport)],
        ['query'],
      ),
    'getSchool' : IDL.Func([IDL.Principal], [IDL.Opt(School)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDailyReport' : IDL.Func([DailyReport], [], []),
    'saveSchool' : IDL.Func([School], [], []),
    'saveSchoolForPrincipal' : IDL.Func([IDL.Principal, School], [], []),
  });
};

export const init = ({ IDL }) => { return []; };