/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyMonitoringRow {
  'report' : [] | [DailyReport],
  'principal' : Principal,
  'school' : School,
}
export interface DailyReport {
  'catatanPresensi' : string,
  'catatanWaliSantri' : string,
  'programProblemSolvingScore' : bigint,
  'waliSantriResponseScore' : bigint,
  'departureTime' : Time,
  'date' : Time,
  'totalScore' : bigint,
  'catatanMonitoringGuru' : string,
  'teacherControlScore' : bigint,
  'catatanPermasalahanProgram' : string,
  'attendanceScore' : bigint,
  'classControlScore' : bigint,
  'catatanAmatanKelas' : string,
  'attendancePhoto' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface RankedDailyReport {
  'kepsek' : Principal,
  'dailyReport' : DailyReport,
}
export interface School {
  'region' : string,
  'active' : boolean,
  'name' : string,
  'principalName' : string,
}
export interface SchoolSummary { 'principal' : Principal, 'school' : School }
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActiveSchoolsCount' : ActorMethod<[], bigint>,
  'getActiveSchoolsList' : ActorMethod<[], Array<SchoolSummary>>,
  'getAllDailyReportsForKepsek' : ActorMethod<[], Array<DailyReport>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyMonitoringRows' : ActorMethod<[Time], Array<DailyMonitoringRow>>,
  'getDailyReport' : ActorMethod<[Principal, Time], [] | [DailyReport]>,
  'getReportsForDate' : ActorMethod<[Time], Array<RankedDailyReport>>,
  'getSchool' : ActorMethod<[Principal], [] | [School]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailyReport' : ActorMethod<[DailyReport], undefined>,
  'saveSchool' : ActorMethod<[School], undefined>,
  'saveSchoolForPrincipal' : ActorMethod<[Principal, School], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];